---
language: python
services: docker

env:
  global:
    - ROLE_NAME: dockerbox
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

before_install:
  - ssh-keygen -t rsa -N '' -f $HOME/.ssh/id_rsa

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test
